### Получить все задачи
GET http://localhost:8080/tasks
Accept: application/json

### Добавить новую задачу
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Купить молоко"
}

### Удалить задачу по id
DELETE http://localhost:8080/tasks/1
